version: '2.1'

networks:
    selenium_grid_internal:

services:
    selenium_hub:
        image: selenium/hub
        container_name: selenium_hub
        privileged: true
        ports:
            - 4444:4444
        expose:
            - "4444"
        environment:
            - GRID_TIMEOUT=120000
            - GRID_BROWSER_TIMEOUT=120000
        networks:
            - selenium_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug
        container_name: nodechrome
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=America/New_York
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        healthcheck:
              test: "exit 0"

    nodechrome_2:
        image: selenium/node-chrome-debug
        container_name: nodechrome_2
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=America/New_York
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        healthcheck:
              test: "exit 0"

    nodechrome_3:
        image: selenium/node-chrome-debug
        container_name: nodechrome_3
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=America/New_York
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        healthcheck:
              test: "exit 0"

    nodechrome_4:
        image: selenium/node-chrome-debug
        container_name: nodechrome_4
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=America/New_York
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        healthcheck:
              test: "exit 0"

    nodefirefox:
        image: selenium/node-firefox-debug
        container_name: nodefirefox
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=America/New_York
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        healthcheck:
              test: "exit 0"

    robotframework:
        image: jepot/sap_hybris_robotframework
        container_name: sap_hybris_robotframework
        privileged: true
        command: top -b
        restart: on-failure
        depends_on:
            nodechrome:
                condition: service_healthy
        networks:
            - selenium_grid_internal
        volumes:
            - ../TestReport/:/volTestResult

    #     volumes_from:
    #            - data_volume
    #
    data_volume:
      image: jepot/sap_hybris_data_volume
      container_name: sap_hybris_data_volume
      volumes:
          - /volTestResult/
          #- /vTestResults/

    #command: ["pybot", "usr/repository/Tests/demo_ch.robot"]
